# Generated by Django 2.1 on 2020-03-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddingDetailsModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=30, unique=True)),
                ('DATE_OF_BIRTH', models.DateField(help_text='dd_mm_yyyy')),
                ('EMAIL_ID', models.EmailField(max_length=30)),
                ('GENDER', models.CharField(max_length=30)),
                ('MOBILE_NO', models.IntegerField()),
                ('ADDRESS', models.CharField(max_length=30)),
                ('USERNAME', models.CharField(max_length=30)),
                ('PASSWORD', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=30)),
                ('PASSWORD', models.CharField(max_length=30)),
            ],
        ),
    ]
