# Generated by Django 2.1 on 2020-03-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addingdetailsmodel',
            old_name='EMAIL_ID',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='addingdetailsmodel',
            old_name='MOBILE_NO',
            new_name='MOBILE',
        ),
    ]
