# Generated by Django 2.1 on 2020-03-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant_login', '0003_auto_20200311_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=30, unique=True)),
                ('DATE_OF_BIRTH', models.DateField(help_text='yyyy-mm-dd')),
                ('EMAIL', models.EmailField(max_length=30)),
                ('GENDER', models.CharField(max_length=30)),
                ('MOBILE', models.IntegerField()),
                ('QUALIFICATION', models.CharField(max_length=30)),
                ('POST', models.FloatField()),
                ('PERCENTAGE', models.FloatField()),
                ('RESUME', models.FileField(upload_to='applicant_document')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicantFormModel',
        ),
    ]
