# Generated by Django 2.1 on 2020-03-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hradmin', '0002_auto_20200212_1159'),
        ('Applicant_login', '0005_interviewapplicantmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterviewApplicantModel',
            new_name='InterviewModel',
        ),
    ]
