# Generated by Django 3.0 on 2020-02-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLOYEENAME', models.CharField(max_length=30, unique=True)),
                ('PASSWORD', models.CharField(max_length=30)),
                ('DESIGNATION', models.CharField(choices=[('MANAGER', 'MANAGER'), ('HRHEAD', 'HRHEAD'), ('INTERVIWER', 'INTERVIWER'), ('EMPLOYEE', 'EMPLOYEE')], max_length=30)),
                ('ADDRESS', models.CharField(max_length=50)),
                ('CONTACTNO', models.IntegerField(max_length=10)),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=30, unique=True)),
                ('PASSWORD', models.CharField(max_length=30)),
            ],
        ),
    ]
