# Generated by Django 3.0 on 2020-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddingDetails',
            fields=[
                ('OPPERTUNITY_CODE', models.IntegerField(primary_key=True, serialize=False)),
                ('QUALIFICATION', models.CharField(max_length=50)),
                ('RESISTARTION_START_FORM', models.DateTimeField()),
                ('AGE_LIMIT', models.IntegerField()),
                ('LAST_DAY_TO_APPLY', models.DateTimeField()),
                ('DEPARTMENT_ID', models.IntegerField()),
                ('NO_OF_POSITION', models.IntegerField()),
                ('DESCRIPTION', models.CharField(max_length=50)),
                ('RESPONSIBILITIES', models.CharField(max_length=50)),
                ('CONTACTNO', models.IntegerField()),
            ],
        ),
    ]
