# Generated by Django 2.1 on 2020-03-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_addingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addingdetails',
            name='DEPARTMENT_ID',
            field=models.CharField(max_length=50),
        ),
    ]
