# Generated by Django 2.1 on 2020-03-12 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant_login', '0006_auto_20200312_0958'),
        ('Hradmin', '0002_auto_20200212_1159'),
        ('manager', '0003_auto_20200310_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerInterviewModel',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Hradmin.AddEmployeeModel')),
                ('Schedule_Date', models.DateField(help_text='yyyy-mm-dd')),
                ('Applicant_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Applicant_login.ApplicationModel')),
            ],
        ),
    ]
