# Generated by Django 2.1 on 2020-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewer_Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewApplicantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interview_ID', models.IntegerField()),
                ('Interviewer', models.IntegerField()),
                ('SCHEDULE_TIMESTAMP', models.DateField(help_text='yyyy-mm-dd')),
                ('Applicant_id', models.IntegerField()),
                ('Result', models.CharField(choices=[('select', 'select'), ('Rejected', 'Rejected')], max_length=30)),
            ],
        ),
    ]
